// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/professors_exams_unipi.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProfessorsExamsUnipi struct {
	ExamName      string `protobuf:"bytes,1,opt,name=examName,proto3" json:"examName,omitempty"`
	ProfessorName string `protobuf:"bytes,2,opt,name=professorName,proto3" json:"professorName,omitempty"`
	ProfessorId   string `protobuf:"bytes,3,opt,name=professorId,proto3" json:"professorId,omitempty"`
	ProfessorKey  string `protobuf:"bytes,4,opt,name=professorKey,proto3" json:"professorKey,omitempty"`
}

func (m *ProfessorsExamsUnipi) Reset()         { *m = ProfessorsExamsUnipi{} }
func (m *ProfessorsExamsUnipi) String() string { return proto.CompactTextString(m) }
func (*ProfessorsExamsUnipi) ProtoMessage()    {}
func (*ProfessorsExamsUnipi) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa6be62c6393c368, []int{0}
}
func (m *ProfessorsExamsUnipi) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfessorsExamsUnipi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfessorsExamsUnipi.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfessorsExamsUnipi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfessorsExamsUnipi.Merge(m, src)
}
func (m *ProfessorsExamsUnipi) XXX_Size() int {
	return m.Size()
}
func (m *ProfessorsExamsUnipi) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfessorsExamsUnipi.DiscardUnknown(m)
}

var xxx_messageInfo_ProfessorsExamsUnipi proto.InternalMessageInfo

func (m *ProfessorsExamsUnipi) GetExamName() string {
	if m != nil {
		return m.ExamName
	}
	return ""
}

func (m *ProfessorsExamsUnipi) GetProfessorName() string {
	if m != nil {
		return m.ProfessorName
	}
	return ""
}

func (m *ProfessorsExamsUnipi) GetProfessorId() string {
	if m != nil {
		return m.ProfessorId
	}
	return ""
}

func (m *ProfessorsExamsUnipi) GetProfessorKey() string {
	if m != nil {
		return m.ProfessorKey
	}
	return ""
}

func init() {
	proto.RegisterType((*ProfessorsExamsUnipi)(nil), "university_chain_it.universitychainit.ProfessorsExamsUnipi")
}

func init() {
	proto.RegisterFile("universitychainit/professors_exams_unipi.proto", fileDescriptor_aa6be62c6393c368)
}

var fileDescriptor_aa6be62c6393c368 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2b, 0xcd, 0xcb, 0x2c,
	0x4b, 0x2d, 0x2a, 0xce, 0x2c, 0xa9, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xcb, 0x2c, 0xd1, 0x2f, 0x28,
	0xca, 0x4f, 0x4b, 0x2d, 0x2e, 0xce, 0x2f, 0x2a, 0x8e, 0x4f, 0xad, 0x48, 0xcc, 0x2d, 0x8e, 0x2f,
	0xcd, 0xcb, 0x2c, 0xc8, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x45, 0xa8, 0x8f, 0x07,
	0x6b, 0x88, 0xcf, 0x2c, 0xc1, 0x34, 0x43, 0x69, 0x1e, 0x23, 0x97, 0x48, 0x00, 0xdc, 0x1c, 0x57,
	0x90, 0x31, 0xa1, 0x20, 0x53, 0x84, 0xa4, 0xb8, 0x38, 0x40, 0x86, 0xfa, 0x25, 0xe6, 0xa6, 0x4a,
	0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x42, 0x2a, 0x5c, 0xbc, 0x70, 0xbb, 0xc1, 0x0a,
	0x98, 0xc0, 0x0a, 0x50, 0x05, 0x85, 0x14, 0xb8, 0xb8, 0xe1, 0x02, 0x9e, 0x29, 0x12, 0xcc, 0x60,
	0x35, 0xc8, 0x42, 0x42, 0x4a, 0x5c, 0x3c, 0x70, 0xae, 0x77, 0x6a, 0xa5, 0x04, 0x0b, 0x58, 0x09,
	0x8a, 0x98, 0x93, 0xfb, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7,
	0x38, 0xe1, 0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0xe9, 0x62,
	0xf1, 0xa1, 0x7e, 0x85, 0x3e, 0x66, 0x38, 0x95, 0x54, 0x16, 0xa4, 0x16, 0x27, 0xb1, 0x81, 0xc3,
	0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x80, 0x09, 0x2f, 0x49, 0x01, 0x00, 0x00,
}

func (m *ProfessorsExamsUnipi) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfessorsExamsUnipi) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfessorsExamsUnipi) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ProfessorKey) > 0 {
		i -= len(m.ProfessorKey)
		copy(dAtA[i:], m.ProfessorKey)
		i = encodeVarintProfessorsExamsUnipi(dAtA, i, uint64(len(m.ProfessorKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ProfessorId) > 0 {
		i -= len(m.ProfessorId)
		copy(dAtA[i:], m.ProfessorId)
		i = encodeVarintProfessorsExamsUnipi(dAtA, i, uint64(len(m.ProfessorId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ProfessorName) > 0 {
		i -= len(m.ProfessorName)
		copy(dAtA[i:], m.ProfessorName)
		i = encodeVarintProfessorsExamsUnipi(dAtA, i, uint64(len(m.ProfessorName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ExamName) > 0 {
		i -= len(m.ExamName)
		copy(dAtA[i:], m.ExamName)
		i = encodeVarintProfessorsExamsUnipi(dAtA, i, uint64(len(m.ExamName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintProfessorsExamsUnipi(dAtA []byte, offset int, v uint64) int {
	offset -= sovProfessorsExamsUnipi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProfessorsExamsUnipi) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ExamName)
	if l > 0 {
		n += 1 + l + sovProfessorsExamsUnipi(uint64(l))
	}
	l = len(m.ProfessorName)
	if l > 0 {
		n += 1 + l + sovProfessorsExamsUnipi(uint64(l))
	}
	l = len(m.ProfessorId)
	if l > 0 {
		n += 1 + l + sovProfessorsExamsUnipi(uint64(l))
	}
	l = len(m.ProfessorKey)
	if l > 0 {
		n += 1 + l + sovProfessorsExamsUnipi(uint64(l))
	}
	return n
}

func sovProfessorsExamsUnipi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozProfessorsExamsUnipi(x uint64) (n int) {
	return sovProfessorsExamsUnipi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProfessorsExamsUnipi) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowProfessorsExamsUnipi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfessorsExamsUnipi: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfessorsExamsUnipi: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExamName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfessorsExamsUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExamName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfessorName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfessorsExamsUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProfessorName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfessorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfessorsExamsUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProfessorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfessorKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowProfessorsExamsUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProfessorKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipProfessorsExamsUnipi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthProfessorsExamsUnipi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipProfessorsExamsUnipi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowProfessorsExamsUnipi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProfessorsExamsUnipi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowProfessorsExamsUnipi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthProfessorsExamsUnipi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupProfessorsExamsUnipi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthProfessorsExamsUnipi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthProfessorsExamsUnipi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowProfessorsExamsUnipi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupProfessorsExamsUnipi = fmt.Errorf("proto: unexpected end of group")
)
