// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/stored_student_unipi.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StoredStudentUnipi struct {
	Index          string               `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	StudentData    *StudentInfo         `protobuf:"bytes,2,opt,name=studentData,proto3" json:"studentData,omitempty"`
	TranscriptData *TranscriptOfRecords `protobuf:"bytes,3,opt,name=transcriptData,proto3" json:"transcriptData,omitempty"`
	PersonalData   *PersonalInfo        `protobuf:"bytes,4,opt,name=personalData,proto3" json:"personalData,omitempty"`
	ResidenceData  *ResidenceInfo       `protobuf:"bytes,5,opt,name=residenceData,proto3" json:"residenceData,omitempty"`
	ContactData    *ContactInfo         `protobuf:"bytes,6,opt,name=contactData,proto3" json:"contactData,omitempty"`
	TaxesData      *TaxesInfo           `protobuf:"bytes,7,opt,name=taxesData,proto3" json:"taxesData,omitempty"`
	ErasmusData    *ErasmusInfo         `protobuf:"bytes,8,opt,name=erasmusData,proto3" json:"erasmusData,omitempty"`
}

func (m *StoredStudentUnipi) Reset()         { *m = StoredStudentUnipi{} }
func (m *StoredStudentUnipi) String() string { return proto.CompactTextString(m) }
func (*StoredStudentUnipi) ProtoMessage()    {}
func (*StoredStudentUnipi) Descriptor() ([]byte, []int) {
	return fileDescriptor_80759ac3af6584a3, []int{0}
}
func (m *StoredStudentUnipi) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredStudentUnipi) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredStudentUnipi.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredStudentUnipi) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredStudentUnipi.Merge(m, src)
}
func (m *StoredStudentUnipi) XXX_Size() int {
	return m.Size()
}
func (m *StoredStudentUnipi) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredStudentUnipi.DiscardUnknown(m)
}

var xxx_messageInfo_StoredStudentUnipi proto.InternalMessageInfo

func (m *StoredStudentUnipi) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *StoredStudentUnipi) GetStudentData() *StudentInfo {
	if m != nil {
		return m.StudentData
	}
	return nil
}

func (m *StoredStudentUnipi) GetTranscriptData() *TranscriptOfRecords {
	if m != nil {
		return m.TranscriptData
	}
	return nil
}

func (m *StoredStudentUnipi) GetPersonalData() *PersonalInfo {
	if m != nil {
		return m.PersonalData
	}
	return nil
}

func (m *StoredStudentUnipi) GetResidenceData() *ResidenceInfo {
	if m != nil {
		return m.ResidenceData
	}
	return nil
}

func (m *StoredStudentUnipi) GetContactData() *ContactInfo {
	if m != nil {
		return m.ContactData
	}
	return nil
}

func (m *StoredStudentUnipi) GetTaxesData() *TaxesInfo {
	if m != nil {
		return m.TaxesData
	}
	return nil
}

func (m *StoredStudentUnipi) GetErasmusData() *ErasmusInfo {
	if m != nil {
		return m.ErasmusData
	}
	return nil
}

func init() {
	proto.RegisterType((*StoredStudentUnipi)(nil), "university_chain_it.universitychainit.StoredStudentUnipi")
}

func init() {
	proto.RegisterFile("universitychainit/stored_student_unipi.proto", fileDescriptor_80759ac3af6584a3)
}

var fileDescriptor_80759ac3af6584a3 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd3, 0xc1, 0x6e, 0xda, 0x30,
	0x18, 0x07, 0x70, 0xb2, 0x0d, 0x36, 0xcc, 0xb6, 0x83, 0xb5, 0x03, 0xe2, 0x10, 0x21, 0x34, 0x26,
	0x0e, 0x23, 0x4c, 0xb0, 0xd3, 0x8e, 0x6b, 0xab, 0xaa, 0x97, 0xb6, 0x0a, 0x54, 0x95, 0xb8, 0x44,
	0x26, 0x71, 0x54, 0x4b, 0xad, 0x1d, 0xd9, 0x4e, 0x05, 0x6f, 0xd1, 0x4b, 0xdf, 0xa9, 0x47, 0x8e,
	0x3d, 0x56, 0xf0, 0x22, 0x55, 0x3e, 0x07, 0x08, 0x4d, 0xa4, 0x86, 0x63, 0xa4, 0xff, 0xf7, 0xf3,
	0xa7, 0xbf, 0x1d, 0xf4, 0x3b, 0xe6, 0xec, 0x9e, 0x4a, 0xc5, 0xf4, 0xc2, 0xbf, 0x21, 0x8c, 0x33,
	0x3d, 0x50, 0x5a, 0x48, 0x1a, 0x78, 0x4a, 0xc7, 0x01, 0xe5, 0xda, 0x8b, 0x39, 0x8b, 0x98, 0x13,
	0x49, 0xa1, 0x05, 0xee, 0xee, 0xd2, 0x1e, 0xc4, 0x3d, 0xa6, 0x9d, 0x9c, 0xd0, 0xfa, 0x59, 0x84,
	0x1a, 0x8d, 0xf1, 0x50, 0x18, 0xac, 0xd5, 0xcf, 0xa7, 0xb4, 0x24, 0x5c, 0xf9, 0x92, 0x45, 0xda,
	0x13, 0xa1, 0x27, 0xa9, 0x2f, 0x64, 0xa0, 0xd2, 0x78, 0x37, 0x1f, 0x8f, 0xa8, 0x54, 0x82, 0x93,
	0xdb, 0xac, 0xfa, 0x2b, 0x1f, 0x93, 0x54, 0xb1, 0x80, 0x72, 0x9f, 0x66, 0x73, 0x05, 0x3b, 0xfa,
	0x82, 0x6b, 0xe2, 0xef, 0xed, 0xd8, 0x29, 0xd8, 0x91, 0xcc, 0xa9, 0x7a, 0x47, 0xa2, 0x92, 0xa8,
	0xbb, 0x38, 0x9b, 0xea, 0x3c, 0x56, 0x11, 0x1e, 0x43, 0xb3, 0x63, 0x53, 0xc5, 0x55, 0xd2, 0x2b,
	0xfe, 0x81, 0xaa, 0x8c, 0x07, 0x74, 0xde, 0xb4, 0xda, 0x56, 0xaf, 0xee, 0x9a, 0x0f, 0x3c, 0x41,
	0x8d, 0xb4, 0xb0, 0x63, 0xa2, 0x49, 0xf3, 0x43, 0xdb, 0xea, 0x35, 0x86, 0x43, 0xa7, 0x54, 0xfb,
	0x4e, 0xea, 0x9f, 0xf1, 0x50, 0xb8, 0x59, 0x06, 0xcf, 0xd0, 0xf7, 0x5d, 0xc1, 0x00, 0x7f, 0x04,
	0xf8, 0x5f, 0x49, 0x78, 0xb2, 0x1d, 0xbe, 0x08, 0x5d, 0x73, 0x37, 0xee, 0x1b, 0x11, 0x5f, 0xa3,
	0xaf, 0x9b, 0x5b, 0x81, 0x13, 0x3e, 0xc1, 0x09, 0xa3, 0x92, 0x27, 0x5c, 0xa6, 0xa3, 0xb0, 0xfb,
	0x1e, 0x84, 0xa7, 0xe8, 0xdb, 0xf6, 0x1e, 0x41, 0xae, 0x82, 0xfc, 0xb7, 0xa4, 0xec, 0x6e, 0x66,
	0x81, 0xde, 0xa7, 0x92, 0xba, 0xd3, 0xbb, 0x07, 0xb9, 0x76, 0x50, 0xdd, 0x47, 0x66, 0xd2, 0xd4,
	0x9d, 0x61, 0xf0, 0x39, 0xaa, 0xc3, 0x5b, 0x01, 0xf3, 0x33, 0x98, 0x7f, 0xca, 0x36, 0x9d, 0xcc,
	0x81, 0xb8, 0x23, 0x92, 0x2d, 0xd3, 0x77, 0x05, 0xe2, 0x97, 0x83, 0xb6, 0x3c, 0x31, 0x93, 0x66,
	0xcb, 0x0c, 0xf3, 0xff, 0xf4, 0x69, 0x65, 0x5b, 0xcb, 0x95, 0x6d, 0xbd, 0xac, 0x6c, 0xeb, 0x61,
	0x6d, 0x57, 0x96, 0x6b, 0xbb, 0xf2, 0xbc, 0xb6, 0x2b, 0xd3, 0x7e, 0x81, 0x3c, 0x98, 0x0f, 0x0a,
	0xfe, 0x88, 0x45, 0x44, 0xd5, 0xac, 0x06, 0xef, 0x7c, 0xf4, 0x1a, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0xe2, 0x0b, 0x3f, 0x52, 0x04, 0x00, 0x00,
}

func (m *StoredStudentUnipi) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredStudentUnipi) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredStudentUnipi) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ErasmusData != nil {
		{
			size, err := m.ErasmusData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.TaxesData != nil {
		{
			size, err := m.TaxesData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.ContactData != nil {
		{
			size, err := m.ContactData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.ResidenceData != nil {
		{
			size, err := m.ResidenceData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.PersonalData != nil {
		{
			size, err := m.PersonalData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.TranscriptData != nil {
		{
			size, err := m.TranscriptData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.StudentData != nil {
		{
			size, err := m.StudentData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintStoredStudentUnipi(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStoredStudentUnipi(dAtA []byte, offset int, v uint64) int {
	offset -= sovStoredStudentUnipi(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredStudentUnipi) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.StudentData != nil {
		l = m.StudentData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.TranscriptData != nil {
		l = m.TranscriptData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.PersonalData != nil {
		l = m.PersonalData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.ResidenceData != nil {
		l = m.ResidenceData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.ContactData != nil {
		l = m.ContactData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.TaxesData != nil {
		l = m.TaxesData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	if m.ErasmusData != nil {
		l = m.ErasmusData.Size()
		n += 1 + l + sovStoredStudentUnipi(uint64(l))
	}
	return n
}

func sovStoredStudentUnipi(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStoredStudentUnipi(x uint64) (n int) {
	return sovStoredStudentUnipi(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredStudentUnipi) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStoredStudentUnipi
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredStudentUnipi: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredStudentUnipi: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StudentData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StudentData == nil {
				m.StudentData = &StudentInfo{}
			}
			if err := m.StudentData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TranscriptData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TranscriptData == nil {
				m.TranscriptData = &TranscriptOfRecords{}
			}
			if err := m.TranscriptData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PersonalData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PersonalData == nil {
				m.PersonalData = &PersonalInfo{}
			}
			if err := m.PersonalData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResidenceData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ResidenceData == nil {
				m.ResidenceData = &ResidenceInfo{}
			}
			if err := m.ResidenceData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContactData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ContactData == nil {
				m.ContactData = &ContactInfo{}
			}
			if err := m.ContactData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaxesData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TaxesData == nil {
				m.TaxesData = &TaxesInfo{}
			}
			if err := m.TaxesData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErasmusData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ErasmusData == nil {
				m.ErasmusData = &ErasmusInfo{}
			}
			if err := m.ErasmusData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStoredStudentUnipi(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStoredStudentUnipi
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStoredStudentUnipi(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStoredStudentUnipi
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStoredStudentUnipi
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStoredStudentUnipi
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStoredStudentUnipi
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStoredStudentUnipi
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStoredStudentUnipi        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStoredStudentUnipi          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStoredStudentUnipi = fmt.Errorf("proto: unexpected end of group")
)
