// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/student_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type StudentInfo struct {
	Name                     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Surname                  string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	CourseType               uint64 `protobuf:"varint,3,opt,name=courseType,proto3" json:"courseType,omitempty"`
	CourseOfStudy            string `protobuf:"bytes,4,opt,name=courseOfStudy,proto3" json:"courseOfStudy,omitempty"`
	Status                   uint64 `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentYearOfStudy       uint64 `protobuf:"varint,6,opt,name=currentYearOfStudy,proto3" json:"currentYearOfStudy,omitempty"`
	OutOfCourse              bool   `protobuf:"varint,7,opt,name=outOfCourse,proto3" json:"outOfCourse,omitempty"`
	NumberOfYearsOutOfCourse uint64 `protobuf:"varint,8,opt,name=numberOfYearsOutOfCourse,proto3" json:"numberOfYearsOutOfCourse,omitempty"`
	StudentKey               string `protobuf:"bytes,9,opt,name=studentKey,proto3" json:"studentKey,omitempty"`
}

func (m *StudentInfo) Reset()         { *m = StudentInfo{} }
func (m *StudentInfo) String() string { return proto.CompactTextString(m) }
func (*StudentInfo) ProtoMessage()    {}
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_81270e748c9b2568, []int{0}
}
func (m *StudentInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StudentInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfo.Merge(m, src)
}
func (m *StudentInfo) XXX_Size() int {
	return m.Size()
}
func (m *StudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfo proto.InternalMessageInfo

func (m *StudentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfo) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *StudentInfo) GetCourseType() uint64 {
	if m != nil {
		return m.CourseType
	}
	return 0
}

func (m *StudentInfo) GetCourseOfStudy() string {
	if m != nil {
		return m.CourseOfStudy
	}
	return ""
}

func (m *StudentInfo) GetStatus() uint64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StudentInfo) GetCurrentYearOfStudy() uint64 {
	if m != nil {
		return m.CurrentYearOfStudy
	}
	return 0
}

func (m *StudentInfo) GetOutOfCourse() bool {
	if m != nil {
		return m.OutOfCourse
	}
	return false
}

func (m *StudentInfo) GetNumberOfYearsOutOfCourse() uint64 {
	if m != nil {
		return m.NumberOfYearsOutOfCourse
	}
	return 0
}

func (m *StudentInfo) GetStudentKey() string {
	if m != nil {
		return m.StudentKey
	}
	return ""
}

func init() {
	proto.RegisterType((*StudentInfo)(nil), "university_chain_it.universitychainit.StudentInfo")
}

func init() {
	proto.RegisterFile("universitychainit/student_info.proto", fileDescriptor_81270e748c9b2568)
}

var fileDescriptor_81270e748c9b2568 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xe3, 0x12, 0xd2, 0xd6, 0x15, 0x8b, 0x07, 0xe4, 0xc9, 0x8a, 0x50, 0x91, 0xb2, 0x90,
	0x0c, 0x6c, 0x8c, 0x30, 0x20, 0xc4, 0x10, 0x29, 0xb0, 0xc0, 0x12, 0xa5, 0xc1, 0x11, 0x1e, 0x6a,
	0x47, 0xfe, 0x41, 0xe4, 0x2d, 0x78, 0x2b, 0x18, 0x3b, 0x32, 0xa2, 0xe4, 0x45, 0x50, 0x6e, 0x5b,
	0x11, 0xd4, 0x76, 0xcb, 0xfd, 0xee, 0x39, 0x27, 0xba, 0x3e, 0x78, 0xee, 0xa4, 0x78, 0xe3, 0xda,
	0x08, 0xdb, 0x94, 0xaf, 0x85, 0x90, 0xc2, 0x26, 0xc6, 0xba, 0x17, 0x2e, 0x6d, 0x2e, 0x64, 0xa5,
	0xe2, 0x5a, 0x2b, 0xab, 0xc8, 0xf9, 0x9f, 0x2a, 0x07, 0x59, 0x2e, 0x6c, 0xbc, 0xe3, 0x3c, 0xfb,
	0x1c, 0xe1, 0xd9, 0xc3, 0xda, 0x7d, 0x27, 0x2b, 0x45, 0x08, 0xf6, 0x65, 0xb1, 0xe4, 0x14, 0x85,
	0x28, 0x9a, 0x66, 0xf0, 0x4d, 0x28, 0x1e, 0x1b, 0xa7, 0x01, 0x8f, 0x00, 0x6f, 0x47, 0xc2, 0x30,
	0x2e, 0x95, 0xd3, 0x86, 0x3f, 0x36, 0x35, 0xa7, 0x47, 0x21, 0x8a, 0xfc, 0x6c, 0x40, 0xc8, 0x1c,
	0x9f, 0xac, 0xa7, 0xb4, 0xea, 0x7f, 0xd2, 0x50, 0x1f, 0xfc, 0xff, 0x21, 0x39, 0xc5, 0x81, 0xb1,
	0x85, 0x75, 0x86, 0x1e, 0x43, 0xc2, 0x66, 0x22, 0x31, 0x26, 0xa5, 0xd3, 0x9a, 0x4b, 0xfb, 0xc4,
	0x0b, 0xbd, 0x8d, 0x08, 0x40, 0xb3, 0x67, 0x43, 0x42, 0x3c, 0x53, 0xce, 0xa6, 0xd5, 0x0d, 0xa4,
	0xd3, 0x71, 0x88, 0xa2, 0x49, 0x36, 0x44, 0xe4, 0x0a, 0x53, 0xe9, 0x96, 0x0b, 0xae, 0xd3, 0xaa,
	0x37, 0x9a, 0x74, 0x20, 0x9f, 0x40, 0xee, 0xc1, 0x7d, 0x7f, 0xeb, 0xe6, 0x99, 0xef, 0x79, 0x43,
	0xa7, 0x70, 0xc8, 0x80, 0x5c, 0xdf, 0x7e, 0xb5, 0x0c, 0xad, 0x5a, 0x86, 0x7e, 0x5a, 0x86, 0x3e,
	0x3a, 0xe6, 0xad, 0x3a, 0xe6, 0x7d, 0x77, 0xcc, 0x7b, 0xbe, 0xd8, 0x53, 0x45, 0xf2, 0x9e, 0xec,
	0xd6, 0x68, 0x9b, 0x9a, 0x9b, 0x45, 0x00, 0x05, 0x5e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x3a,
	0x75, 0xb2, 0x21, 0xe8, 0x01, 0x00, 0x00,
}

func (m *StudentInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StudentInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StudentInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StudentKey) > 0 {
		i -= len(m.StudentKey)
		copy(dAtA[i:], m.StudentKey)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.StudentKey)))
		i--
		dAtA[i] = 0x4a
	}
	if m.NumberOfYearsOutOfCourse != 0 {
		i = encodeVarintStudentInfo(dAtA, i, uint64(m.NumberOfYearsOutOfCourse))
		i--
		dAtA[i] = 0x40
	}
	if m.OutOfCourse {
		i--
		if m.OutOfCourse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.CurrentYearOfStudy != 0 {
		i = encodeVarintStudentInfo(dAtA, i, uint64(m.CurrentYearOfStudy))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintStudentInfo(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	if len(m.CourseOfStudy) > 0 {
		i -= len(m.CourseOfStudy)
		copy(dAtA[i:], m.CourseOfStudy)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.CourseOfStudy)))
		i--
		dAtA[i] = 0x22
	}
	if m.CourseType != 0 {
		i = encodeVarintStudentInfo(dAtA, i, uint64(m.CourseType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Surname) > 0 {
		i -= len(m.Surname)
		copy(dAtA[i:], m.Surname)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.Surname)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintStudentInfo(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStudentInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovStudentInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StudentInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	l = len(m.Surname)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	if m.CourseType != 0 {
		n += 1 + sovStudentInfo(uint64(m.CourseType))
	}
	l = len(m.CourseOfStudy)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovStudentInfo(uint64(m.Status))
	}
	if m.CurrentYearOfStudy != 0 {
		n += 1 + sovStudentInfo(uint64(m.CurrentYearOfStudy))
	}
	if m.OutOfCourse {
		n += 2
	}
	if m.NumberOfYearsOutOfCourse != 0 {
		n += 1 + sovStudentInfo(uint64(m.NumberOfYearsOutOfCourse))
	}
	l = len(m.StudentKey)
	if l > 0 {
		n += 1 + l + sovStudentInfo(uint64(l))
	}
	return n
}

func sovStudentInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStudentInfo(x uint64) (n int) {
	return sovStudentInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StudentInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStudentInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StudentInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StudentInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Surname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Surname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CourseType", wireType)
			}
			m.CourseType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CourseType |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CourseOfStudy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CourseOfStudy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentYearOfStudy", wireType)
			}
			m.CurrentYearOfStudy = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentYearOfStudy |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutOfCourse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OutOfCourse = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NumberOfYearsOutOfCourse", wireType)
			}
			m.NumberOfYearsOutOfCourse = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NumberOfYearsOutOfCourse |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StudentKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStudentInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StudentKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStudentInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStudentInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStudentInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStudentInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStudentInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStudentInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStudentInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStudentInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStudentInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStudentInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStudentInfo = fmt.Errorf("proto: unexpected end of group")
)
