// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgConfigureChain struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgConfigureChain) Reset()         { *m = MsgConfigureChain{} }
func (m *MsgConfigureChain) String() string { return proto.CompactTextString(m) }
func (*MsgConfigureChain) ProtoMessage()    {}
func (*MsgConfigureChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_5083021dc5214058, []int{0}
}
func (m *MsgConfigureChain) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfigureChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfigureChain.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfigureChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfigureChain.Merge(m, src)
}
func (m *MsgConfigureChain) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfigureChain) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfigureChain.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfigureChain proto.InternalMessageInfo

func (m *MsgConfigureChain) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgConfigureChainResponse struct {
	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *MsgConfigureChainResponse) Reset()         { *m = MsgConfigureChainResponse{} }
func (m *MsgConfigureChainResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfigureChainResponse) ProtoMessage()    {}
func (*MsgConfigureChainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5083021dc5214058, []int{1}
}
func (m *MsgConfigureChainResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfigureChainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfigureChainResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfigureChainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfigureChainResponse.Merge(m, src)
}
func (m *MsgConfigureChainResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfigureChainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfigureChainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfigureChainResponse proto.InternalMessageInfo

func (m *MsgConfigureChainResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

type MsgRegisterNewStudent struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	University     string `protobuf:"bytes,2,opt,name=university,proto3" json:"university,omitempty"`
	Name           string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname        string `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	CourseType     string `protobuf:"bytes,5,opt,name=courseType,proto3" json:"courseType,omitempty"`
	CourseOfStudy  string `protobuf:"bytes,6,opt,name=courseOfStudy,proto3" json:"courseOfStudy,omitempty"`
	DepartmentName string `protobuf:"bytes,7,opt,name=departmentName,proto3" json:"departmentName,omitempty"`
}

func (m *MsgRegisterNewStudent) Reset()         { *m = MsgRegisterNewStudent{} }
func (m *MsgRegisterNewStudent) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterNewStudent) ProtoMessage()    {}
func (*MsgRegisterNewStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_5083021dc5214058, []int{2}
}
func (m *MsgRegisterNewStudent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterNewStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterNewStudent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterNewStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterNewStudent.Merge(m, src)
}
func (m *MsgRegisterNewStudent) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterNewStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterNewStudent.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterNewStudent proto.InternalMessageInfo

func (m *MsgRegisterNewStudent) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterNewStudent) GetUniversity() string {
	if m != nil {
		return m.University
	}
	return ""
}

func (m *MsgRegisterNewStudent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MsgRegisterNewStudent) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *MsgRegisterNewStudent) GetCourseType() string {
	if m != nil {
		return m.CourseType
	}
	return ""
}

func (m *MsgRegisterNewStudent) GetCourseOfStudy() string {
	if m != nil {
		return m.CourseOfStudy
	}
	return ""
}

func (m *MsgRegisterNewStudent) GetDepartmentName() string {
	if m != nil {
		return m.DepartmentName
	}
	return ""
}

type MsgRegisterNewStudentResponse struct {
	StudentIndex string `protobuf:"bytes,1,opt,name=studentIndex,proto3" json:"studentIndex,omitempty"`
}

func (m *MsgRegisterNewStudentResponse) Reset()         { *m = MsgRegisterNewStudentResponse{} }
func (m *MsgRegisterNewStudentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterNewStudentResponse) ProtoMessage()    {}
func (*MsgRegisterNewStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5083021dc5214058, []int{3}
}
func (m *MsgRegisterNewStudentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterNewStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterNewStudentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterNewStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterNewStudentResponse.Merge(m, src)
}
func (m *MsgRegisterNewStudentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterNewStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterNewStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterNewStudentResponse proto.InternalMessageInfo

func (m *MsgRegisterNewStudentResponse) GetStudentIndex() string {
	if m != nil {
		return m.StudentIndex
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgConfigureChain)(nil), "university_chain_it.universitychainit.MsgConfigureChain")
	proto.RegisterType((*MsgConfigureChainResponse)(nil), "university_chain_it.universitychainit.MsgConfigureChainResponse")
	proto.RegisterType((*MsgRegisterNewStudent)(nil), "university_chain_it.universitychainit.MsgRegisterNewStudent")
	proto.RegisterType((*MsgRegisterNewStudentResponse)(nil), "university_chain_it.universitychainit.MsgRegisterNewStudentResponse")
}

func init() { proto.RegisterFile("universitychainit/tx.proto", fileDescriptor_5083021dc5214058) }

var fileDescriptor_5083021dc5214058 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xbb, 0xfd, 0x8b, 0x83, 0x16, 0x5c, 0x50, 0x62, 0xc1, 0x20, 0x41, 0xc5, 0x4b, 0x53,
	0xb0, 0x17, 0x0f, 0x1e, 0xc4, 0x0a, 0xe2, 0xa1, 0x15, 0xa2, 0x27, 0x2f, 0x25, 0xb6, 0xd3, 0x98,
	0x43, 0x37, 0x61, 0x77, 0xa3, 0xcd, 0x3b, 0x78, 0xf0, 0xe8, 0x5b, 0xf8, 0x1a, 0x1e, 0x7b, 0xf4,
	0x28, 0xed, 0xd9, 0x77, 0x90, 0x6c, 0xfa, 0xc7, 0x36, 0x11, 0x8a, 0xde, 0x32, 0xbf, 0x99, 0xf9,
	0xf6, 0xdb, 0x7c, 0x2c, 0x54, 0x02, 0xe6, 0x3e, 0x22, 0x17, 0xae, 0x0c, 0x3b, 0x0f, 0xb6, 0xcb,
	0x5c, 0x59, 0x93, 0x03, 0xd3, 0xe7, 0x9e, 0xf4, 0xe8, 0xc1, 0xbc, 0xd7, 0x56, 0xcd, 0xb6, 0x2b,
	0xcd, 0xc4, 0xbc, 0x51, 0x85, 0xcd, 0xa6, 0x70, 0x1a, 0x1e, 0xeb, 0xb9, 0x4e, 0xc0, 0xb1, 0x11,
	0x61, 0xaa, 0x41, 0xa9, 0xc3, 0xd1, 0x96, 0x1e, 0xd7, 0xc8, 0x1e, 0x39, 0x5a, 0xb3, 0xa6, 0xa5,
	0x51, 0x87, 0x9d, 0xc4, 0xb8, 0x85, 0xc2, 0xf7, 0x98, 0x40, 0xba, 0x0d, 0x45, 0x21, 0x6d, 0x19,
	0x08, 0xb5, 0x55, 0xb0, 0x26, 0x95, 0xf1, 0x45, 0x60, 0xab, 0x29, 0x1c, 0x0b, 0x1d, 0x57, 0x48,
	0xe4, 0x2d, 0x7c, 0xba, 0x91, 0x41, 0x17, 0x99, 0xfc, 0xfd, 0x20, 0xaa, 0x03, 0xcc, 0xcd, 0x6a,
	0x59, 0xd5, 0xfc, 0x41, 0x28, 0x85, 0x3c, 0xb3, 0xfb, 0xa8, 0xe5, 0x54, 0x47, 0x7d, 0x47, 0x6a,
	0x22, 0xe0, 0x0a, 0xe7, 0x63, 0xb5, 0x49, 0x19, 0xa9, 0x75, 0xbc, 0x80, 0x0b, 0xbc, 0x0d, 0x7d,
	0xd4, 0x0a, 0xb1, 0xda, 0x9c, 0xd0, 0x7d, 0xd8, 0x88, 0xab, 0xeb, 0x5e, 0x64, 0x2d, 0xd4, 0x8a,
	0x6a, 0x64, 0x11, 0xd2, 0x43, 0x28, 0x77, 0xd1, 0xb7, 0xb9, 0xec, 0x23, 0x93, 0xad, 0xe8, 0x98,
	0x92, 0x1a, 0x5b, 0xa2, 0x46, 0x03, 0x76, 0x53, 0xaf, 0x3b, 0xfb, 0x51, 0x06, 0xac, 0x8b, 0x18,
	0x5d, 0xb1, 0x2e, 0x0e, 0x26, 0x77, 0x5f, 0x60, 0xc7, 0x6f, 0x59, 0xc8, 0x35, 0x85, 0x43, 0x9f,
	0x09, 0x94, 0x97, 0xe2, 0x39, 0x31, 0x57, 0xca, 0xd6, 0x4c, 0x24, 0x55, 0x39, 0xfb, 0xeb, 0xe6,
	0xcc, 0xfa, 0x2b, 0x01, 0x9a, 0x12, 0xe4, 0xe9, 0xea, 0xc2, 0xc9, 0xed, 0xca, 0xc5, 0x7f, 0xb6,
	0xa7, 0xd6, 0xce, 0x2f, 0xdf, 0x47, 0x3a, 0x19, 0x8e, 0x74, 0xf2, 0x39, 0xd2, 0xc9, 0xcb, 0x58,
	0xcf, 0x0c, 0xc7, 0x7a, 0xe6, 0x63, 0xac, 0x67, 0xee, 0xaa, 0x29, 0xf2, 0xb5, 0x41, 0x2d, 0xe5,
	0xf5, 0x84, 0x3e, 0x8a, 0xfb, 0xa2, 0x7a, 0x41, 0xf5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6b,
	0x1b, 0xf2, 0x1f, 0x5f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ConfigureChain(ctx context.Context, in *MsgConfigureChain, opts ...grpc.CallOption) (*MsgConfigureChainResponse, error)
	RegisterNewStudent(ctx context.Context, in *MsgRegisterNewStudent, opts ...grpc.CallOption) (*MsgRegisterNewStudentResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ConfigureChain(ctx context.Context, in *MsgConfigureChain, opts ...grpc.CallOption) (*MsgConfigureChainResponse, error) {
	out := new(MsgConfigureChainResponse)
	err := c.cc.Invoke(ctx, "/university_chain_it.universitychainit.Msg/ConfigureChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterNewStudent(ctx context.Context, in *MsgRegisterNewStudent, opts ...grpc.CallOption) (*MsgRegisterNewStudentResponse, error) {
	out := new(MsgRegisterNewStudentResponse)
	err := c.cc.Invoke(ctx, "/university_chain_it.universitychainit.Msg/RegisterNewStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ConfigureChain(context.Context, *MsgConfigureChain) (*MsgConfigureChainResponse, error)
	RegisterNewStudent(context.Context, *MsgRegisterNewStudent) (*MsgRegisterNewStudentResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ConfigureChain(ctx context.Context, req *MsgConfigureChain) (*MsgConfigureChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureChain not implemented")
}
func (*UnimplementedMsgServer) RegisterNewStudent(ctx context.Context, req *MsgRegisterNewStudent) (*MsgRegisterNewStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNewStudent not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ConfigureChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfigureChain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfigureChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_chain_it.universitychainit.Msg/ConfigureChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfigureChain(ctx, req.(*MsgConfigureChain))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterNewStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterNewStudent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterNewStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/university_chain_it.universitychainit.Msg/RegisterNewStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterNewStudent(ctx, req.(*MsgRegisterNewStudent))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "university_chain_it.universitychainit.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureChain",
			Handler:    _Msg_ConfigureChain_Handler,
		},
		{
			MethodName: "RegisterNewStudent",
			Handler:    _Msg_RegisterNewStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "universitychainit/tx.proto",
}

func (m *MsgConfigureChain) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfigureChain) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfigureChain) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfigureChainResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfigureChainResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfigureChainResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterNewStudent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterNewStudent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterNewStudent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DepartmentName) > 0 {
		i -= len(m.DepartmentName)
		copy(dAtA[i:], m.DepartmentName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DepartmentName)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CourseOfStudy) > 0 {
		i -= len(m.CourseOfStudy)
		copy(dAtA[i:], m.CourseOfStudy)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CourseOfStudy)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CourseType) > 0 {
		i -= len(m.CourseType)
		copy(dAtA[i:], m.CourseType)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CourseType)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Surname) > 0 {
		i -= len(m.Surname)
		copy(dAtA[i:], m.Surname)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Surname)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.University) > 0 {
		i -= len(m.University)
		copy(dAtA[i:], m.University)
		i = encodeVarintTx(dAtA, i, uint64(len(m.University)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterNewStudentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterNewStudentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterNewStudentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StudentIndex) > 0 {
		i -= len(m.StudentIndex)
		copy(dAtA[i:], m.StudentIndex)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StudentIndex)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgConfigureChain) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfigureChainResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovTx(uint64(m.Status))
	}
	return n
}

func (m *MsgRegisterNewStudent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.University)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Surname)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CourseType)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CourseOfStudy)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DepartmentName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterNewStudentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StudentIndex)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgConfigureChain) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfigureChain: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfigureChain: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfigureChainResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfigureChainResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfigureChainResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterNewStudent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterNewStudent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterNewStudent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field University", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.University = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Surname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Surname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CourseType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CourseType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CourseOfStudy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CourseOfStudy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DepartmentName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DepartmentName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterNewStudentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterNewStudentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterNewStudentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StudentIndex", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StudentIndex = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
