// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/university_info_uniroma_1.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UniversityInfoUniroma1 struct {
	NextStudentId   uint64 `protobuf:"varint,1,opt,name=nextStudentId,proto3" json:"nextStudentId,omitempty"`
	SecretariatKey  string `protobuf:"bytes,2,opt,name=secretariatKey,proto3" json:"secretariatKey,omitempty"`
	UniversityKey   string `protobuf:"bytes,3,opt,name=universityKey,proto3" json:"universityKey,omitempty"`
	CaiKey          string `protobuf:"bytes,4,opt,name=caiKey,proto3" json:"caiKey,omitempty"`
	FifoHeadErasmus string `protobuf:"bytes,5,opt,name=fifoHeadErasmus,proto3" json:"fifoHeadErasmus,omitempty"`
	FifoTailErasmus string `protobuf:"bytes,6,opt,name=fifoTailErasmus,proto3" json:"fifoTailErasmus,omitempty"`
	DeadlineTaxes   string `protobuf:"bytes,7,opt,name=deadlineTaxes,proto3" json:"deadlineTaxes,omitempty"`
	DeadlineErasmus string `protobuf:"bytes,8,opt,name=deadlineErasmus,proto3" json:"deadlineErasmus,omitempty"`
}

func (m *UniversityInfoUniroma1) Reset()         { *m = UniversityInfoUniroma1{} }
func (m *UniversityInfoUniroma1) String() string { return proto.CompactTextString(m) }
func (*UniversityInfoUniroma1) ProtoMessage()    {}
func (*UniversityInfoUniroma1) Descriptor() ([]byte, []int) {
	return fileDescriptor_0820934d92c47136, []int{0}
}
func (m *UniversityInfoUniroma1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UniversityInfoUniroma1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UniversityInfoUniroma1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UniversityInfoUniroma1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniversityInfoUniroma1.Merge(m, src)
}
func (m *UniversityInfoUniroma1) XXX_Size() int {
	return m.Size()
}
func (m *UniversityInfoUniroma1) XXX_DiscardUnknown() {
	xxx_messageInfo_UniversityInfoUniroma1.DiscardUnknown(m)
}

var xxx_messageInfo_UniversityInfoUniroma1 proto.InternalMessageInfo

func (m *UniversityInfoUniroma1) GetNextStudentId() uint64 {
	if m != nil {
		return m.NextStudentId
	}
	return 0
}

func (m *UniversityInfoUniroma1) GetSecretariatKey() string {
	if m != nil {
		return m.SecretariatKey
	}
	return ""
}

func (m *UniversityInfoUniroma1) GetUniversityKey() string {
	if m != nil {
		return m.UniversityKey
	}
	return ""
}

func (m *UniversityInfoUniroma1) GetCaiKey() string {
	if m != nil {
		return m.CaiKey
	}
	return ""
}

func (m *UniversityInfoUniroma1) GetFifoHeadErasmus() string {
	if m != nil {
		return m.FifoHeadErasmus
	}
	return ""
}

func (m *UniversityInfoUniroma1) GetFifoTailErasmus() string {
	if m != nil {
		return m.FifoTailErasmus
	}
	return ""
}

func (m *UniversityInfoUniroma1) GetDeadlineTaxes() string {
	if m != nil {
		return m.DeadlineTaxes
	}
	return ""
}

func (m *UniversityInfoUniroma1) GetDeadlineErasmus() string {
	if m != nil {
		return m.DeadlineErasmus
	}
	return ""
}

func init() {
	proto.RegisterType((*UniversityInfoUniroma1)(nil), "university_chain_it.universitychainit.UniversityInfoUniroma1")
}

func init() {
	proto.RegisterFile("universitychainit/university_info_uniroma_1.proto", fileDescriptor_0820934d92c47136)
}

var fileDescriptor_0820934d92c47136 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0x80, 0xbb, 0xfd, 0xfb, 0x47, 0x5d, 0x50, 0x21, 0x87, 0x92, 0xd3, 0x52, 0x44, 0x25, 0x17,
	0x1b, 0x82, 0x6f, 0x20, 0x88, 0x16, 0x6f, 0xb5, 0xbd, 0x78, 0x09, 0x6b, 0x32, 0xc1, 0x81, 0x76,
	0xb7, 0xec, 0x6e, 0x24, 0x79, 0x0b, 0x1f, 0xab, 0xc7, 0x1e, 0x3d, 0x4a, 0xf2, 0x22, 0x92, 0xc4,
	0x98, 0x26, 0xf5, 0x98, 0x6f, 0xbe, 0x7c, 0x3b, 0x30, 0xd4, 0x4f, 0x04, 0xbe, 0x83, 0xd2, 0x68,
	0xb2, 0xf0, 0x8d, 0xa3, 0x40, 0xe3, 0xb5, 0x24, 0x40, 0x11, 0xcb, 0x20, 0x11, 0xa8, 0xe4, 0x9a,
	0x07, 0xfe, 0x74, 0xa3, 0xa4, 0x91, 0xf6, 0xd5, 0x9e, 0x50, 0xfd, 0x13, 0xa0, 0x99, 0x1e, 0x64,
	0x2e, 0xb6, 0x43, 0x3a, 0x5e, 0xfe, 0xd2, 0x99, 0x88, 0xe5, 0xb2, 0x0e, 0xf9, 0xf6, 0x25, 0x3d,
	0x15, 0x90, 0x9a, 0x67, 0x93, 0x44, 0x20, 0xcc, 0x2c, 0x72, 0xc8, 0x84, 0xb8, 0xa3, 0x79, 0x17,
	0xda, 0xd7, 0xf4, 0x4c, 0x43, 0xa8, 0xc0, 0x70, 0x85, 0xdc, 0x3c, 0x41, 0xe6, 0x0c, 0x27, 0xc4,
	0x3d, 0x99, 0xf7, 0x68, 0x59, 0x6b, 0x5f, 0x2f, 0xb5, 0x7f, 0x95, 0xd6, 0x85, 0xf6, 0x98, 0x5a,
	0x21, 0xc7, 0x72, 0x3c, 0xaa, 0xc6, 0x3f, 0x5f, 0xb6, 0x4b, 0xcf, 0x63, 0x8c, 0xe5, 0x23, 0xf0,
	0xe8, 0x5e, 0x71, 0xbd, 0x4e, 0xb4, 0xf3, 0xbf, 0x12, 0xfa, 0xb8, 0x31, 0x17, 0x1c, 0x57, 0x8d,
	0x69, 0xb5, 0xe6, 0x1e, 0x2e, 0x37, 0x8a, 0x80, 0x47, 0x2b, 0x14, 0xb0, 0xe0, 0x29, 0x68, 0xe7,
	0xa8, 0xde, 0xa8, 0x03, 0xcb, 0x5e, 0x03, 0x9a, 0xde, 0x71, 0xdd, 0xeb, 0xe1, 0xbb, 0x87, 0x6d,
	0xce, 0xc8, 0x2e, 0x67, 0xe4, 0x2b, 0x67, 0xe4, 0xa3, 0x60, 0x83, 0x5d, 0xc1, 0x06, 0x9f, 0x05,
	0x1b, 0xbc, 0xdc, 0xfc, 0x71, 0x0b, 0x2f, 0xf5, 0x0e, 0x8f, 0x6a, 0xb2, 0x0d, 0xe8, 0x57, 0xab,
	0xba, 0xe0, 0xed, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x73, 0xdb, 0xdb, 0xb8, 0xf6, 0x01, 0x00,
	0x00,
}

func (m *UniversityInfoUniroma1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UniversityInfoUniroma1) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversityInfoUniroma1) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeadlineErasmus) > 0 {
		i -= len(m.DeadlineErasmus)
		copy(dAtA[i:], m.DeadlineErasmus)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.DeadlineErasmus)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DeadlineTaxes) > 0 {
		i -= len(m.DeadlineTaxes)
		copy(dAtA[i:], m.DeadlineTaxes)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.DeadlineTaxes)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.FifoTailErasmus) > 0 {
		i -= len(m.FifoTailErasmus)
		copy(dAtA[i:], m.FifoTailErasmus)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.FifoTailErasmus)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.FifoHeadErasmus) > 0 {
		i -= len(m.FifoHeadErasmus)
		copy(dAtA[i:], m.FifoHeadErasmus)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.FifoHeadErasmus)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.CaiKey) > 0 {
		i -= len(m.CaiKey)
		copy(dAtA[i:], m.CaiKey)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.CaiKey)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.UniversityKey) > 0 {
		i -= len(m.UniversityKey)
		copy(dAtA[i:], m.UniversityKey)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.UniversityKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SecretariatKey) > 0 {
		i -= len(m.SecretariatKey)
		copy(dAtA[i:], m.SecretariatKey)
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(len(m.SecretariatKey)))
		i--
		dAtA[i] = 0x12
	}
	if m.NextStudentId != 0 {
		i = encodeVarintUniversityInfoUniroma_1(dAtA, i, uint64(m.NextStudentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintUniversityInfoUniroma_1(dAtA []byte, offset int, v uint64) int {
	offset -= sovUniversityInfoUniroma_1(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UniversityInfoUniroma1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextStudentId != 0 {
		n += 1 + sovUniversityInfoUniroma_1(uint64(m.NextStudentId))
	}
	l = len(m.SecretariatKey)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	l = len(m.UniversityKey)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	l = len(m.CaiKey)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	l = len(m.FifoHeadErasmus)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	l = len(m.FifoTailErasmus)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	l = len(m.DeadlineTaxes)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	l = len(m.DeadlineErasmus)
	if l > 0 {
		n += 1 + l + sovUniversityInfoUniroma_1(uint64(l))
	}
	return n
}

func sovUniversityInfoUniroma_1(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUniversityInfoUniroma_1(x uint64) (n int) {
	return sovUniversityInfoUniroma_1(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UniversityInfoUniroma1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUniversityInfoUniroma_1
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UniversityInfoUniroma1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UniversityInfoUniroma1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextStudentId", wireType)
			}
			m.NextStudentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextStudentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretariatKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretariatKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversityKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniversityKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CaiKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CaiKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FifoHeadErasmus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FifoHeadErasmus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FifoTailErasmus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FifoTailErasmus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadlineTaxes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeadlineTaxes = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeadlineErasmus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeadlineErasmus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUniversityInfoUniroma_1(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUniversityInfoUniroma_1
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUniversityInfoUniroma_1(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUniversityInfoUniroma_1
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUniversityInfoUniroma_1
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUniversityInfoUniroma_1
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUniversityInfoUniroma_1
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUniversityInfoUniroma_1
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUniversityInfoUniroma_1        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUniversityInfoUniroma_1          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUniversityInfoUniroma_1 = fmt.Errorf("proto: unexpected end of group")
)
