// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: universitychainit/university_details.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UniversityDetails struct {
	UniversityName string           `protobuf:"bytes,1,opt,name=universityName,proto3" json:"universityName,omitempty"`
	ProfessorsInfo *ProfessorsExams `protobuf:"bytes,2,opt,name=professorsInfo,proto3" json:"professorsInfo,omitempty"`
	UniversityData *UniversityInfo  `protobuf:"bytes,3,opt,name=universityData,proto3" json:"universityData,omitempty"`
	StudentDetails *StoredStudent   `protobuf:"bytes,4,opt,name=studentDetails,proto3" json:"studentDetails,omitempty"`
}

func (m *UniversityDetails) Reset()         { *m = UniversityDetails{} }
func (m *UniversityDetails) String() string { return proto.CompactTextString(m) }
func (*UniversityDetails) ProtoMessage()    {}
func (*UniversityDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_238ea1015835fe76, []int{0}
}
func (m *UniversityDetails) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UniversityDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UniversityDetails.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UniversityDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniversityDetails.Merge(m, src)
}
func (m *UniversityDetails) XXX_Size() int {
	return m.Size()
}
func (m *UniversityDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UniversityDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UniversityDetails proto.InternalMessageInfo

func (m *UniversityDetails) GetUniversityName() string {
	if m != nil {
		return m.UniversityName
	}
	return ""
}

func (m *UniversityDetails) GetProfessorsInfo() *ProfessorsExams {
	if m != nil {
		return m.ProfessorsInfo
	}
	return nil
}

func (m *UniversityDetails) GetUniversityData() *UniversityInfo {
	if m != nil {
		return m.UniversityData
	}
	return nil
}

func (m *UniversityDetails) GetStudentDetails() *StoredStudent {
	if m != nil {
		return m.StudentDetails
	}
	return nil
}

func init() {
	proto.RegisterType((*UniversityDetails)(nil), "university_chain_it.universitychainit.UniversityDetails")
}

func init() {
	proto.RegisterFile("universitychainit/university_details.proto", fileDescriptor_238ea1015835fe76)
}

var fileDescriptor_238ea1015835fe76 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0xcd, 0xcb, 0x2c,
	0x4b, 0x2d, 0x2a, 0xce, 0x2c, 0xa9, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xcb, 0x2c, 0xd1, 0x47, 0x88,
	0xc4, 0xa7, 0xa4, 0x96, 0x24, 0x66, 0xe6, 0x14, 0xeb, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xa9,
	0x22, 0xc9, 0x80, 0x15, 0xc7, 0x67, 0x96, 0xe8, 0x61, 0xe8, 0x97, 0xd2, 0xc0, 0x34, 0xb2, 0xa0,
	0x28, 0x3f, 0x2d, 0xb5, 0xb8, 0x38, 0xbf, 0xa8, 0x38, 0x3e, 0xb5, 0x22, 0x31, 0x17, 0x6a, 0xa0,
	0x94, 0x3a, 0x5e, 0xcb, 0x33, 0xf3, 0xd2, 0xf2, 0xa1, 0x0a, 0xd5, 0x30, 0x15, 0x16, 0x97, 0xe4,
	0x17, 0xa5, 0xa6, 0xc4, 0x17, 0x97, 0x94, 0xa6, 0xa4, 0xe6, 0x95, 0x40, 0xd4, 0x29, 0xdd, 0x60,
	0xe2, 0x12, 0x0c, 0x85, 0x2b, 0x75, 0x81, 0xb8, 0x5e, 0x48, 0x8d, 0x8b, 0x0f, 0xa1, 0xdf, 0x2f,
	0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x4d, 0x54, 0x28, 0x8e, 0x8b, 0x0f,
	0xe1, 0x50, 0xcf, 0xbc, 0xb4, 0x7c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x33, 0x3d, 0xa2,
	0x3c, 0xae, 0x17, 0x00, 0xd7, 0xec, 0x0a, 0xf2, 0x64, 0x10, 0x9a, 0x69, 0x42, 0xb1, 0xc8, 0xee,
	0x70, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x06, 0x9b, 0x6f, 0x4a, 0xa4, 0xf9, 0x08, 0x9f, 0x81, 0x8c,
	0x0b, 0x42, 0x33, 0x4c, 0x28, 0x86, 0x8b, 0x0f, 0x1a, 0x1a, 0x50, 0x8f, 0x4b, 0xb0, 0x80, 0x8d,
	0x37, 0x21, 0xd2, 0xf8, 0x60, 0x70, 0x88, 0x06, 0x43, 0x8c, 0x08, 0x42, 0x33, 0xcb, 0xc9, 0xfd,
	0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e,
	0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x74, 0xb1, 0x18, 0xaf, 0x5f, 0xa1,
	0x8f, 0x19, 0x65, 0x25, 0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0xe0, 0xa8, 0x32, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xa7, 0x41, 0x08, 0x32, 0x7a, 0x02, 0x00, 0x00,
}

func (m *UniversityDetails) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UniversityDetails) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UniversityDetails) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.StudentDetails != nil {
		{
			size, err := m.StudentDetails.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUniversityDetails(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.UniversityData != nil {
		{
			size, err := m.UniversityData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUniversityDetails(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.ProfessorsInfo != nil {
		{
			size, err := m.ProfessorsInfo.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUniversityDetails(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UniversityName) > 0 {
		i -= len(m.UniversityName)
		copy(dAtA[i:], m.UniversityName)
		i = encodeVarintUniversityDetails(dAtA, i, uint64(len(m.UniversityName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintUniversityDetails(dAtA []byte, offset int, v uint64) int {
	offset -= sovUniversityDetails(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UniversityDetails) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UniversityName)
	if l > 0 {
		n += 1 + l + sovUniversityDetails(uint64(l))
	}
	if m.ProfessorsInfo != nil {
		l = m.ProfessorsInfo.Size()
		n += 1 + l + sovUniversityDetails(uint64(l))
	}
	if m.UniversityData != nil {
		l = m.UniversityData.Size()
		n += 1 + l + sovUniversityDetails(uint64(l))
	}
	if m.StudentDetails != nil {
		l = m.StudentDetails.Size()
		n += 1 + l + sovUniversityDetails(uint64(l))
	}
	return n
}

func sovUniversityDetails(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUniversityDetails(x uint64) (n int) {
	return sovUniversityDetails(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UniversityDetails) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUniversityDetails
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UniversityDetails: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UniversityDetails: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversityName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityDetails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UniversityName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProfessorsInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityDetails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ProfessorsInfo == nil {
				m.ProfessorsInfo = &ProfessorsExams{}
			}
			if err := m.ProfessorsInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UniversityData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityDetails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UniversityData == nil {
				m.UniversityData = &UniversityInfo{}
			}
			if err := m.UniversityData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StudentDetails", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUniversityDetails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StudentDetails == nil {
				m.StudentDetails = &StoredStudent{}
			}
			if err := m.StudentDetails.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUniversityDetails(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUniversityDetails
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUniversityDetails(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUniversityDetails
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUniversityDetails
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUniversityDetails
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUniversityDetails
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUniversityDetails
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUniversityDetails
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUniversityDetails        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUniversityDetails          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUniversityDetails = fmt.Errorf("proto: unexpected end of group")
)
